In [9]:
import pandas as pd
data = pd.read_csv("heart_statlog_cleveland_hungary_final.csv")
X = data.iloc[:, :-1]
y = data.iloc[:, -1]
data.head()

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,1,2,140,289,0,0,172,0,0.0,1,0
1,49,0,3,160,180,0,0,156,0,1.0,2,1
2,37,1,2,130,283,0,1,98,0,0.0,1,0
3,48,0,4,138,214,0,0,108,1,1.5,2,1
4,54,1,3,150,195,0,0,122,0,0.0,1,0

In [10]:
# import logistic regression
from sklearn.linear_model import LogisticRegression
# standard scaler
from sklearn.preprocessing import StandardScaler
# save to pickle
import pickle

In [11]:
model = LogisticRegression()
scaler = StandardScaler()
X = scaler.fit_transform(X)
model.fit(X, y)
print(model.score(X, y))

# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))
filename = 'scaler.sav'
pickle.dump(scaler, open(filename, 'wb'))

0.83109243697479

In [12]:
# load model and scaler
model = pickle.load(open('models/best_model.pickle', 'rb'))
scaler = pickle.load(open('models/used_scaler.pickle', 'rb'))

In [49]:
row_df = data.iloc[[2, 8, 1], :-1]
row_df

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope
2,37,1,2,130,283,0,1,98,0,0.0,1
8,37,1,4,140,207,0,0,130,1,1.5,2
1,49,0,3,160,180,0,0,156,0,1.0,2

In [50]:
scaled_row = scaler.transform(row_df)
print(scaled_row)
model.predict_proba(scaled_row)

[[-1.75359899  0.57411579 -1.33116726 -0.09342104  0.7114992  -0.53199518
   0.3582735  -1.63061631 -0.80439967 -0.85208237 -1.02511546]
 [-1.75359899  0.57411579  0.81675008  0.45932496 -0.03220398 -0.53199518
  -0.78627808 -0.38547042  1.24316312  0.52389142  0.60140107]
 [-0.49039735 -1.74180892 -0.25720859  1.56481697 -0.29641431 -0.53199518
  -0.78627808  0.62621062 -0.80439967  0.06523349  0.60140107]]

array([[0.99, 0.01],
       [0.07, 0.93],
       [0.23, 0.77]])

In [51]:
# show min and max value of each column
data.describe().loc[['min', 'max']].T

                      min    max
age                  28.0   77.0
sex                   0.0    1.0
chest pain type       1.0    4.0
resting bp s          0.0  200.0
cholesterol           0.0  603.0
fasting blood sugar   0.0    1.0
resting ecg           0.0    2.0
max heart rate       60.0  202.0
exercise angina       0.0    1.0
oldpeak              -2.6    6.2
ST slope              0.0    3.0
target                0.0    1.0